# Generated by Django 5.2.14 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_remove_linktrace_is_masked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.URLField(
                blank=True,
                help_text="Profile picture URL from the OIDC provider, if any.",
                max_length=500,
                null=True,
                verbose_name="picture",
            ),
        ),
    ]
